/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Result of performing an Admin Path operation
type IsAdminPathResponse struct {
	// True if the input IP address is an Admin Path, and false otherwise
	IsAdminPathNode bool `json:"IsAdminPathNode,omitempty"`
	// True if the operation was successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
}
