/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Individual item to detect for XXE
type XxeDetectionRequestItem struct {
	// Individual input text item to protect from XXE
	InputText string `json:"InputText,omitempty"`
	// Optional: Set to true to allow Internet-based dependency URLs for DTDs and other XML External Entitites, set to false to block.  Default is false.
	AllowInternetUrls bool `json:"AllowInternetUrls,omitempty"`
	// Optional: Comma separated list of fully-qualified URLs that will automatically be considered safe.
	KnownSafeUrls []string `json:"KnownSafeUrls,omitempty"`
	// Optional: Comma separated list of fully-qualified URLs that will automatically be considered unsafe.
	KnownUnsafeUrls []string `json:"KnownUnsafeUrls,omitempty"`
}
