/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Input to a batch SQL Injection detection operation
type SqlInjectionCheckBatchRequest struct {
	// Multiple items to detect for SQL Injection
	RequestItems []SqlInjectionCheckRequestItem `json:"RequestItems,omitempty"`
	// Set to Normal to target a high-security SQL Injection detection level with a very low false positive rate; select High to target a very-high security SQL Injection detection level with higher false positives.  Default is Normal (recommended).
	DetectionLevel string `json:"DetectionLevel,omitempty"`
}
