/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Result of performing a get public holidays request operation
type PublicHolidaysResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Public holidays in the requested country and year
	PublicHolidays []PublicHolidayOccurrence `json:"PublicHolidays,omitempty"`
}
