/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Request to reverse geocode a Street Address
type ReverseGeocodeAddressRequest struct {
	// Latitude coordinate in WGS84 format
	Latitude float64 `json:"Latitude,omitempty"`
	// Longitude coordinate in WGS84 format
	Longitude float64 `json:"Longitude,omitempty"`
}
