/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Result of checking a URL for SSRF threats
type UrlSsrfResponseFull struct {
	// True if the URL is clean, false if it is at risk of containing an SSRF threat or attack
	CleanURL bool `json:"CleanURL,omitempty"`
	// Threat level of the URL; possible values are High, Medium, Low and None
	ThreatLevel string `json:"ThreatLevel,omitempty"`
}
