/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

import (
	"time"
)

// Result of performing a date time parsing
type DateTimeStandardizedParseResponse struct {
	// True if successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Result of performing a date time parsing
	ParsedDateResult time.Time `json:"ParsedDateResult,omitempty"`
	// Year of the parsed date time result
	Year int32 `json:"Year,omitempty"`
	// Month of the parsed date time result
	Month int32 `json:"Month,omitempty"`
	// Day of the parsed date time result
	Day int32 `json:"Day,omitempty"`
	// Hour of the parsed date time result (24-hour)
	Hour int32 `json:"Hour,omitempty"`
	// Minute of the parsed date time result
	Minute int32 `json:"Minute,omitempty"`
	// Second of the parsed date time result
	Second int32 `json:"Second,omitempty"`
	// Day of week
	DayOfWeek string `json:"DayOfWeek,omitempty"`
}
