/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Result of reverse geocoding a street address
type ReverseGeocodeAddressResponse struct {
	// True if the address operation was successful, false otherwise
	Successful bool `json:"Successful,omitempty"`
	// Street address to validate, such as '2950 Buskirk Ave.'
	StreetAddress string `json:"StreetAddress,omitempty"`
	// City part of the addrerss to validate, such as 'Walnut Creek'
	City string `json:"City,omitempty"`
	// State or province of the address to validate, such as 'CA' or 'California'
	StateOrProvince string `json:"StateOrProvince,omitempty"`
	// Zip code or postal code of the address to validate, such as '94597'
	PostalCode string `json:"PostalCode,omitempty"`
	// Name of the country, such as 'United States'.  Global countries are supported.
	CountryFullName string `json:"CountryFullName,omitempty"`
	// Three-letter ISO 3166-1 country code
	CountryCode string `json:"CountryCode,omitempty"`
}
