/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Details of one country
type CountryDetails struct {
	// Name of the country
	CountryName string `json:"CountryName,omitempty"`
	// Three-letter ISO 3166-1 country code
	ThreeLetterCode string `json:"ThreeLetterCode,omitempty"`
	// Two-letter ISO 3166-1 country code
	ISOTwoLetterCode string `json:"ISOTwoLetterCode,omitempty"`
	// True if this country is currently a member of the European Union (EU), false otherwise
	IsEuropeanUnionMember bool `json:"IsEuropeanUnionMember,omitempty"`
	// ISO 4217 currency three-letter code associated with the country
	ISOCurrencyCode string `json:"ISOCurrencyCode,omitempty"`
	// Symbol associated with the currency
	CurrencySymbol string `json:"CurrencySymbol,omitempty"`
	// Full name of the currency
	CurrencyEnglishName string `json:"CurrencyEnglishName,omitempty"`
}
