/*
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveValidateApiClient

// Geolocation street address result
type GeolocateStreetAddressResponse struct {
	// Two-letter country code of IP address
	CountryCode string `json:"CountryCode,omitempty"`
	// Country name of IP address
	CountryName string `json:"CountryName,omitempty"`
	// Street address of IP address
	StreetAddress string `json:"StreetAddress,omitempty"`
	// City of IP address
	City string `json:"City,omitempty"`
	// State/region of IP address
	RegionName string `json:"RegionName,omitempty"`
	// Zip or postal code of IP address
	ZipCode string `json:"ZipCode,omitempty"`
}
